CREATE PROC FI_SP_IncBeneficiarioV2
    @NOME          VARCHAR (50),
	@CPF		   VARCHAR (11),
	@IDCLIENTE	   BIGINT
AS
BEGIN
	IF NOT EXISTS(SELECT CPF FROM dbo.BENEFICIARIOS WHERE CPF = @CPF)
		BEGIN
		INSERT INTO BENEFICIARIOS(NOME, CPF, IDCLIENTE) 
		VALUES (@NOME, @CPF, @IDCLIENTE)
		SELECT SCOPE_IDENTITY()
		END
	ELSE
		BEGIN
		RAISERROR('CPF já cadastrado!', 16, 1)
		END
END